### PR TITLE
add info about ENB plugin

### PR DESCRIPTION
**Pull request by verybigman**

### CODE REVIEW

**Comment by ai** [comment]
Awesome. Did it pass a PostCSS Runner Guidelines (you can find it in docs directory)?

**Comment by verybigman** [comment]
Ok, find it:)

**Comment by ai** [comment]
I checked it. Nope, it doesn’t pass Guidelines. I will accept PR only when we will fix it. I wil create a issue.

**Comment by ai** [comment]
https://github.com/theprotein/enb-postcss/issues/1

**Comment by verybigman** [comment]
Ok, wait theprotein/enb-postcss#1. I work on it

**Comment by verybigman** [comment]
All done! https://github.com/theprotein/enb-postcss/commit/6b79de948a9749e8c6a5e22a80902f9319e163e0

**Comment by ai** [comment]
Great work. Merged.

**Pull request merged**
