### PR TITLE
Add css-property-sorter to readme

### PR DESCRIPTION
**Pull request by Siilwyn**

### CODE REVIEW

**Comment by ai** [comment]
Awesom project! :D

I will promote it in PostCSS twitter on this week

**Comment by Siilwyn** [comment]
Wow, that was a fast merge.
Thanks! Looking forward to the tweet. :smiley_cat:

**Comment by himynameisdave** [comment]
Totally nullifies this plugin I was working on: [`postcss-alphabetize`](https://github.com/himynameisdave/postcss-alphabetize) :anguished:

**Comment by Siilwyn** [comment]
Aw, that's a bummer @himynameisdave...

**Comment by Siilwyn** [comment]
Aw, that's a bummer @himynameisdave...

**Comment by himynameisdave** [comment]
@Siilwyn not at all, yours is a better solution & I plan on learning from how yours is :smile:

**Comment by ai** [comment]
@himynameisdave `postcss-alphabetize` is not a good name, because there are many reasons why people afraid alphabetical sort. For example, the largest Russian team Yandex prefer CSSComb approach.

**Comment by Siilwyn** [comment]
Aw, that's a bummer @himynameisdave...

**Comment by himynameisdave** [comment]
@ai yeah cool, it's not published to NPM so that namespace is still available. I was making it for myself basically because we have a certain CSS formatting guide that we follow where I work. Yes, we are aware that the order of declarations matters and that there are times when you don't want to declare things alphabetically. Anyways I don't need to build mine anymore because @Siilwyn's [sorter plugin](https://github.com/Siilwyn/css-property-sorter) will do perfect and so I am going to delete my alphabetize plugin. :+1:

**Pull request merged**
