### PR TITLE
add postcss-zoom-font-size

### PR DESCRIPTION
**Pull request by talgautb**

### CODE REVIEW

**Comment by ai** [comment]
Use correct order ;). ABC with `postcss-` prefix in the front.

**Comment by ai** [comment]
Also what is a difference with https://github.com/admdh/postcss-increase-text-sizes ?

**Comment by talgautb** [comment]
@ai hm, :((((((((((( i didn't see it

**Comment by talgautb** [comment]
no such plugin [here](https://github.com/postcss/postcss/blob/master/docs/plugins.md) ((

**Comment by ai** [comment]
I posted it in PostCSS Twitter account and even in VK public ;)

**Comment by ai** [comment]
@admdh you should add your tools to plugin list

**Comment by admdh** [comment]
@ai pull request on it's way!

**Comment by admdh** [comment]
i'm sorry for delay!

**Comment by talgautb** [comment]
my plugin work good for me, @admdh 's plugin not working ((

**Comment by admdh** [comment]
@talgautb what exactly doesn't work?

**Pull request closed without merging**
