### PR TITLE
add rollup-plugin-postcss

### PR DESCRIPTION
**Pull request by egoist**

### CODE REVIEW

**Comment by egoist** [comment]
well, `Rollup` is considered typo...

**Comment by TrySound** [comment]
@egoist You shouldn't use sync postcss api. It's only for debug. You should use promises which could be returned in transform method.

**Comment by egoist** [comment]
gotcha.

**Comment by egoist** [comment]
Now using the Promise.

**Comment by TrySound** [comment]
@egoist postcss own return promise. You don't need to wrap it in new one.

**Comment by egoist** [comment]
@TrySound 😂 sorry for that, fixed.

**Comment by TrySound** [comment]
@egoist Can you show some real world usage example?

**Comment by egoist** [comment]
@TrySound sure, later I'll add some to that repo.

**Comment by ai** [comment]
@egoist sorry, I will compress Rollup link to one line (like Grunt or Brunch) because it is not so popular yet.

**Pull request merged**
