### PR TITLE
Add postcss-hexrgba to README

### PR DESCRIPTION
**Pull request by seaneking**
https://github.com/seaneking/postcss-hexrgba

### CODE REVIEW

**Comment by ai** [comment]
I thought that we have this feature in cssnext. Do we?

**Comment by MoOx** [comment]
This is not valid CSS.
You can do that in cssnext by using `color(#fff a(.2))` (via postcss-color-function)

**Comment by ai** [comment]
OK, I will accept PR when I will be in hotel. I think we need to fix spellchecker dictionary to fix a Travis

**Comment by seaneking** [comment]
yep not aiming to be to-spec css, just a shortcut for those already using rgba(). But just saw https://github.com/avanes/postcss-color-alpha which is similar, just a different syntax. Up to you whether you want to include this variation in the readme or not, as it is quite similar (I personally prefer adding to the existing rgba() format, rather than adding a new decl/value)

**Comment by ben-eb** [comment]
You have two typos in there; `rbga` and `shorthad`.

**Comment by seaneking** [comment]
derp, sorry I'll fix it.

**Comment by seaneking** [comment]
erroring on rgba (suggests rgb), so I guess the spellchecker would need to be updated.

**Pull request merged**
