### PR TITLE
allow multiple words in property

### PR DESCRIPTION
**Pull request by mahtd**
This fixes postcss/postcss-scss#5
Not sure if this is direction you want to go, but it collects as many words it can find into the property

### CODE REVIEW

**Comment by ai** [comment]
Do you test it? ;)

**Comment by ai** [comment]
Released in 5.0.5. Thanks :).

**Comment by ai** [comment]
@mahtd what is your Twitter name?

**Comment by mahtd** [comment]
Yeah, I tested it :)

I'm mattduckman on Twitter, although I don't really use it

**Pull request merged**
