### PR TITLE
Add postcss-reverse-media to readme

### PR DESCRIPTION
**Pull request by MadLittleMods**
[`postcss-reverse-media`](https://github.com/MadLittleMods/postcss-reverse-media)

> Reverse/Invert media query parameters

Input:
```css
@media reverse (max-width: 150px) { /*...*/ }
@media reverse (min-width: 150px) { /*...*/ }
```

Output:
```
@media (min-width: 150.001px) { /*...*/ }
@media (max-width: 149.999px) { /*...*/ }
```

### CODE REVIEW

**Comment by ben-eb** [comment]
Couple of fixes first, please:

* `postcss-plugin` in package.json https://github.com/postcss/postcss/blob/master/docs/guidelines/plugin.md#44-include-postcss-plugin-keyword-in-packagejson
* You have duplicate author and license keys in package.json, which is correct?

**Comment by MadLittleMods** [comment]
@ben-eb Thanks for spotting those :grinning:

Fixed!

**Comment by ben-eb** [comment]
Cool, thanks. :+1:

**Comment by himynameisdave** [comment]
Already [added to `postcss-plugins`](https://github.com/himynameisdave/postcss-plugins/commit/d34e962d3d54fb0ea357ce027b2ad0ca9e91fd8a) list

**Pull request merged**
