### PR TITLE
Add recovery mode for tokenizer & highlighter for terminal

### PR DESCRIPTION
**Pull request by andreypopp**
Do not merge yet.

### CODE REVIEW

**Comment by ai** [comment]
We already have safe parser. I will pick your code manually.

**Comment by andreypopp** [comment]
Oh, did I miss something?

**Comment by andreypopp** [comment]
I see: postcss safe parser.

Well at least you can use highlighter :)

**Comment by ai** [comment]
I moved all commits to `vapula` branch.

**Comment by ai** [comment]
https://github.com/postcss/postcss/commit/30e055b3cb0cfbc909a68445d134b71ab9a983c3
https://github.com/postcss/postcss/commit/7f9754a4fefbef41fdc2bca5d717a66b2db99b71

**Comment by andreypopp** [comment]
Ok, just a reminder that safe tokeniser isn't finished in this commit (some off-by-one errors with error reporting code).

**Pull request closed without merging**
