### PR TITLE
Add postcss-pseudoelements to README.md

### PR DESCRIPTION
**Pull request by sventschui**

### CODE REVIEW

**Comment by ai** [comment]
Could you please make plugin description shorter? In one line like any other plugin.

**Comment by sventschui** [comment]
Done

**Comment by MoOx** [comment]
just to let you know https://github.com/cssnext/cssnext/issues/81 ;)

**Comment by sventschui** [comment]
@ai Any other requirements to be able to merge this PR?

**Comment by ai** [comment]
Nope, only shorter description

**Pull request closed without merging**
