### PR TITLE
Add postcss-sorting to plugins list

### PR DESCRIPTION
**Pull request by hudochenkov**
[postcss-sorting](https://github.com/hudochenkov/postcss-sorting) is a plugin to sort rules content with specified order.

### CODE REVIEW

**Comment by TrySound** [comment]
Seems like duplicating [css-property-sorter](https://github.com/Siilwyn/css-property-sorter). Also it does not follow guidelines. Plugin should use async methods where it's possible.

**Comment by hudochenkov** [comment]
@TrySound it's absolutely not duplicating. css-property-sorter sort only properties. My plugin sort also at-rules, nested rules, variables; can group nodes. Also not breaks nesting (css-property-sorter does). css-property-sorter sorts only _properties_ (plugin name and readme very clear about this) in not nested rules, my plugin sort _all_ rule's content in nested (or not) rules.

About async I agree. I don't know how to replace sync with async yet.

**Comment by TrySound** [comment]
@hudochenkov U can see in css-property-sorter. Are you sure that rules sorting not breaks rendered styles?

**Comment by hudochenkov** [comment]
@TrySound as I tested on complex stylesheets it's not break styles. Style rendering done by PostCSS itself. Obviously edge cases may exists, no one can write software without bugs :)

**Pull request merged**
