### PR TITLE
Add postcss-media-variables

### PR DESCRIPTION
**Pull request by WolfgangKluge**

### CODE REVIEW

**Comment by ai** [comment]
Can you please order your plugin by ABC and link by length?

**Comment by WolfgangKluge** [comment]
Oops. Didn't recognized the order. Sorry.

**Comment by WolfgangKluge** [comment]
postcss-bem
postcss-each
postcss-for
postcss-conditionals

**Comment by ai** [comment]
Oops. Can you make a commit to this PR with `postcss-conditionals` fix too?

**Comment by WolfgangKluge** [comment]
There are some more links in wrong order. I will change it tomorrow.

**Comment by ai** [comment]
Note that `postcss-` prefix. Correct form is:

postcss-a
postcss-z
a
z

**Comment by ben-eb** [comment]
Re-ordering looks good to me. Thanks :+1:

**Pull request merged**
