### PR TITLE
Add postcss-hidden to Shortcuts in the README.

### PR DESCRIPTION
**Pull request by lukelarsen**

### CODE REVIEW

**Comment by ben-eb** [comment]
Nice plugin, thanks! Can you write some tests for plugin guidelines compatibility, please?

https://github.com/postcss/postcss/blob/master/docs/guidelines/plugin.md#21-plugin-must-be-tested

**Comment by lukelarsen** [comment]
@ben-eb Yeah I'll look into it. I'm primarily a designer. Sometimes code stuff comes slow to me. I'll get learning about testing it though. Thanks.

**Comment by ben-eb** [comment]
Feel free to re-use my tests; simple input/output testing.

https://github.com/ben-eb/postcss-minify-font-weight/blob/master/test.js

**Comment by lukelarsen** [comment]
Thanks!

**Comment by ai** [comment]
@lukelarsen ping me when you will finish tests.

**Comment by ai** [comment]
@lukelarsen any updates?

**Comment by lukelarsen** [comment]
I can almost get to this. Work has been really busy and I've been busy preparing for the holidays coming up. I've never done testing like this so I plan on going through @ben-eb example to figure it out.

**Comment by ben-eb** [comment]
@lukelarsen Any updates? Would you like me to send you a pull request for tests?

**Comment by lukelarsen** [comment]
Yes a pull request would be helpful. I'm just slammed at work and have a freelance project going. This is towards the bottom of the list right now... sorry and thanks for checking in.

**Comment by ben-eb** [comment]
Done. https://github.com/lukelarsen/postcss-hidden/pull/5

**Comment by ben-eb** [comment]
We changed the readme since this was submitted so I made a fresh pull request.

https://github.com/postcss/postcss/pull/704

**Pull request closed without merging**
