### PR TITLE
Adds links to modular-scale and color-scale to Language Features sect…

### PR DESCRIPTION
**Pull request by kristoferjoseph**
…ion of the README.

### CODE REVIEW

**Comment by ben-eb** [comment]
Can you ensure that the modules are passing the plugin guidelines?

* `postcss-plugin` keyword, not `postcssplugin`.
* Provide an input and output example on your README.

**Comment by ai** [comment]
@kristoferjoseph please ping me when you will fix a plugin guidelines. They are very important for PostCSS ecosystem.

**Comment by kristoferjoseph** [comment]
I made the updates you suggested. Let me know if there is anything else needed. Thank you.
Input output examples added:
https://github.com/kristoferjoseph/postcss-color-scale
https://github.com/kristoferjoseph/postcss-modular-scale
Keyword updated in package.json:
https://github.com/kristoferjoseph/postcss-color-scale/blob/master/package.json#L8
https://github.com/kristoferjoseph/postcss-modular-scale/blob/master/package.json#L8

**Comment by ai** [comment]
Awesome :)

**Comment by ben-eb** [comment]
@kristoferjoseph Great, thanks! :+1:

**Pull request merged**
