### PR TITLE
Add postcss-sprites plugin

### PR DESCRIPTION
**Pull request by vvasilev-**

### CODE REVIEW

**Comment by ben-eb** [comment]
Can you make sure it passes the plugin guidelines? I checked the source code and you are not passing these:

* https://github.com/postcss/postcss/blob/master/docs/guidelines/plugin.md#14-create-plugin-by-postcssplugin
* https://github.com/postcss/postcss/blob/master/docs/guidelines/plugin.md#21-plugin-must-be-tested
* https://github.com/postcss/postcss/blob/master/docs/guidelines/plugin.md#42-put-input-and-output-examples
* https://github.com/postcss/postcss/blob/master/docs/guidelines/plugin.md#44-postcss-plugin-keyword-in-packagejson

**Comment by ai** [comment]
@ben-eb fuck I miss your comment :(

**Comment by ben-eb** [comment]
Too quick for me. :smile:

**Comment by ai** [comment]
I created issue there https://github.com/2createStudio/postcss-sprites/issues/2

**Pull request merged**
