### PR TITLE
add source to NodeNewProps interface

### PR DESCRIPTION
**Pull request by sylvainpolletvillard**

### CODE REVIEW

**Comment by ai** [comment]
Thanks:). Should I wait for other PR before release?

**Comment by sylvainpolletvillard** [comment]
I checked other interfaces and could not find anything. But I feel sick and can't think properly at the moment. Don't expect any other PR from me tonight

**Comment by ai** [comment]
I will release it tomorrow evening if you didn’t find anything new.

Get well =^_^=

**Comment by hzlmn** [comment]
@ai I have few additions as well will push PR in few hours :)

**Comment by ai** [comment]
Released in 6.0.19

**Pull request merged**
