### PR TITLE
Add postcss-stylestats to plugins.md

### PR DESCRIPTION
**Pull request by kubosho**
:)

### CODE REVIEW

**Comment by ai** [comment]
You need add to docs use cases.

How users will use this output JSON?

Input/output examples should always be useful and oriented to clients.

**Comment by ai** [comment]
Input/output example is part of [Plugin Guidelines](https://github.com/postcss/postcss/blob/master/docs/guidelines/plugin.md). Repo with big JSON is not clear output example ;). Users should see a benefits.

**Comment by ai** [comment]
Ping me, when you will fix it.

**Comment by kubosho** [comment]
@ai I fixed it (add input/output example) 👍

**Comment by ai** [comment]
Why users should care about JSON? :)

if your plugin is plugin for StyleStats, show a stylestats output in output example ;).

Also input example should be a CSS. So user will undestand the stats.

**Comment by kubosho** [comment]
I see.

**Comment by kubosho** [comment]
@ai Fixed it! ;)

**Comment by ai** [comment]
Please, also add a StyleStats output. Users don't know why they need a JSON. Show final use case.

**Comment by kubosho** [comment]
@ai Should I do like https://github.com/cssstats/cssstats-core/tree/master/test ?

**Comment by ai** [comment]
I think you should display stylestats console output.

**Comment by kubosho** [comment]
@ai I understood. It means that you should do the same display as https://github.com/t32k/stylestats#usage

**Comment by ai** [comment]
Yeap

**Comment by kubosho** [comment]
I plan to fix at https://github.com/kubosho/postcss-stylestats/issues/1 in a few days...

**Comment by kubosho** [comment]
Thank you for review. It was very helpful.

**Pull request merged**
