### PR TITLE
Fix TypeScript module export

### PR DESCRIPTION
**Pull request by jedmao**
Sorry, @ai. I must not have copied over this one line properly, so I'm getting an error that postcss is not a function. Sorry about that.

### CODE REVIEW

**Comment by ai** [comment]
I will release it in few days. Is it OK?

**Comment by jedmao** [comment]
Totally fine, thanks!

**Comment by longlho** [comment]
I think this is breaking due to the generated `postcss` dist file having:
```js
exports.default = postcss;
module.exports = exports['default'];
```

so `import postcss from 'postcss'` is broken due to `default` not exposed.

**Comment by jedmao** [comment]
Thanks @longlho. I realize that's what's breaking it. It's just unclear how to fix it from a compiler options standpoint.

**Comment by longlho** [comment]
might have been the `add-module-exports` plugin in babel :-/

**Comment by jedmao** [comment]
@longlho what version of TS are you using?

**Comment by longlho** [comment]
I'm using `2.1.5`

**Pull request merged**
