### PR TITLE
New plugin

### PR DESCRIPTION
**Pull request by ayhankuru**

### CODE REVIEW

**Comment by ai** [comment]
You forget to add link to plugin. Also you should mention plugin name in commit.

Wait second one (but I am going to sleep, so maybe I will accept it tomorrow in the morning).

**Comment by ayhankuru** [comment]
@ai thanks fixed soon :+1:

**Comment by TrySound** [comment]
@ayhankuru It's not plugin. It's wrapper of module with own parser. Won't be accepted.

**Comment by ben-eb** [comment]
I am also :-1: on this.

**Comment by ai** [comment]
I looked into plugin too. Maybe crass is a good tool, but it is not good way to use it.

Stringifing and reparsing may cause unexpected behavior.

It is better just to run crass in old way after PostCSS.

**Pull request closed without merging**
