### PR TITLE
Improve README introduction

### LINKED ISSUE #1156: Improve Readme Introduction
This project is really great but I think you could help newcomers a big deal by changing the readme introduction a little bit. I think it is right now a little to complicated to be easily understood. I am thinking about something like this after the first sentence:
> Put simply, `postcss` transforms CSS into an "abstract syntax tree" (AST) which provides an extensive API to analyze its rules iteratively. This API can then be used by [plugins](https://github.com/postcss/postcss#plugins) to do any arbitrary operation on these rules, like eg. linting or automatic vendor prefixes.

Not sure if this is 100% accurate but I think you get the point. Something like this would have helped me greatly to understand what postcss does at first glance.

### PR DESCRIPTION
**Pull request by kschiffer**
Closes #1156

### CODE REVIEW

**Comment by ai** [comment]
Spelling check failed. I will fix it tomorrow (also make phrase more easy for non-native speakers).

**Comment by kschiffer** [comment]
I gave it another shot which hopefully makes it clearer and also addresses the linting issues. Feel free to modify further to improve clarity.
Keep up the good work! 👍

**Comment by kschiffer** [comment]
Great to see this merged! Just noticed a small typo though:
> e.g. to find errors or **automatically** insert vendor prefixes.

**Comment by ai** [comment]
@kschiffer oops. Fixed.

**Comment by wenliangdai** [comment]
@ai Yes, I will do that today.

**Pull request merged**
