### PR TITLE
Add Plugin postcss-start-to-end

### PR DESCRIPTION
**Pull request by sandrina-p**
This is my first _from scratch_ plugin that I built today all day long!

> [PostCSS](https://github.com/postcss/postcss) plugin that let you control your layout (`ltr` or `rtl`) through logical rather than direction / physical rules.

- [Postcss-plugin-boilerplated](https://github.com/postcss/postcss-plugin-boilerplate) was used
- [Postcss-plugin-guidelines](https://github.com/postcss/postcss/blob/master/docs/guidelines/plugin.md) were followed
- Yarn was used as dependency manager
- Travis is being used as CI service
- The plugin itself has 100% coverage with Jest.
- It is published on [npm](https://www.npmjs.com/package/postcss-start-to-end)
- I'm trying to add [Coveralls](https://coveralls.io/github/sandrina-p/postcss-start-to-end) as coverage reporter, but I'am having troubles.

Thank you, I learned a lot today! 🎉  🤓 

Note: Within the plugin there is a bonus script, _convert_, that is not tested at all, but it will be soon! I first need to learn more about NodeJS.

### CODE REVIEW

**Comment by ai** [comment]
Thanks. Great plugin :+1:

**Comment by sandrina-p** [comment]
Thank you @ai ! 

Perhaps you could help me out to understand what am I missing to integrate [Coveralls](https://coveralls.io/github/sandrina-p/postcss-start-to-end) to my project. I don't get their instructions... It is all working on Travis side as well (I think)

**Comment by ai** [comment]
Sorry, I had no experience in Coveralls. But maybe in out gitter chat somebody could help: https://gitter.im/postcss/postcss

**Comment by michael-ciniawsky** [comment]
@sandrina-p Add this of to your `.travis.yml` file for coverage to work 😛 

**package.json**
```json
{
   "test": "jest --coverage"
}
```
**travis.yml**
```yaml
after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
```

**Comment by sandrina-p** [comment]
@michael-ciniawsky Thank you for your help!

I did what you said, also added `coveralls` to package.json as `--dev`.

I created a new [PR](https://github.com/sandrina-p/postcss-start-to-end/pull/2/files) with the changes that [passed on Travis](https://travis-ci.org/sandrina-p/postcss-start-to-end/builds/227311425) but on [Coveralls](https://coveralls.io/github/sandrina-p/postcss-start-to-end) is still all the same.
What am I missing here? 🤔

**Pull request merged**
