### PR TITLE
Edits from Root node to end

### PR DESCRIPTION
**Pull request by davidtheclark**
I made it all the way through. Some edits are above Root node because I tried to clean up the links a little bit, to make it easier to just throw in links to different parts of the documentation,  and address some of the clarifications you made.

### CODE REVIEW

**Comment by ai** [comment]
Nice. Common part with links is very useful to maintain crosslinks.

**Comment by davidtheclark** [comment]
I forgot to bring up two points that I was thinking about:

- There is no section for `root.toResult()`. Could you add one?
- I was wondering why the `semicolon` properties on `atrule` and `rule` return `true`/`undefined` instead of `true`/`false`. Would you mind explaining the intention?

**Comment by ai** [comment]
Parser just not add `semicolon` property, when we don’t need it. Reason is to make tests and inspect cleaner.

**Comment by ai** [comment]
Oops, sorry, I forgot about `toResult`. Done 2f841fa

**Pull request merged**
