### PR TITLE
Adds Initial Contributing Guidelines.

### PR DESCRIPTION
**Pull request by solodynamo**

### CODE REVIEW

**Comment by ai** [comment]
It is a regular advice for any project.

For example, the most popular PR is new plugins to `docs/plugins.md`. This doc doesn’t cover it.

I suggest you to write the most popular cases first and only then start to make docs.

**Comment by ai** [comment]
It is CSS parser. Most of developers never will change parser or AST ;).

For all this years I had only few PR for source map, parser or AST. So we should not focused on regular PR as in other projects.

**Comment by ai** [comment]
Also we should cover “where can I help” topic. If user what to contribute to PostCSS, but don’t know how it can be useful.

**Comment by solodynamo** [comment]
Okay , will come up with something incorporating most of the above suggestions :)

**Pull request closed without merging**
