### PR TITLE
Add links to my two new plugins

### PR DESCRIPTION
**Pull request by hallvors**
These plugins add the functionality demonstrated on http://hallvord.com/temp/moz/cssfixme.htm to PostCSS

### CODE REVIEW

**Comment by ai** [comment]
Awesome. I will add it soon.

**Comment by ai** [comment]
@yisibl I will happy with this two plugins. They convert `-webkit-` gradient and flexbox to unprefixed versions.

**Comment by ai** [comment]
@hallvors can you send a PR to Autoprefixer docs?

**Comment by ai** [comment]
@hallvors you can, for example, add one more section to Autoprefixer FAQ

**Comment by yisibl** [comment]
Great!

**Pull request merged**
