### PR TITLE
Fix tests on Windows

### LINKED ISSUE #445: Tests fail on Windows
I have 28 tests failing on Windows, I think mostly due to file path issues. Unfortunately, it's rather hard to fix, because it's reading a large JSON file and checking the equality in some tests (e.g., [this line](https://github.com/postcss/postcss/blob/ac8c257ed5ae77ea688f2e5a20e88d743427250a/test/parse.js#L52)).

Mocha gives the following error in that case:
```
          "source": {
              "input": {
                  "css": "a {\n\tcolor: black\n}\n",
                  "safe": false,
     -            "file": "z:\\tab.css",
     -            "from": "z:\\tab.css"
     +            "file": "/tab.css",
     +            "from": "/tab.css"
              }
          },
```

Any suggestions on a strategy to fix this? I'm willing to help.

### PR DESCRIPTION
**Pull request by jedmao**
Fixes #445 

@ai I'm almost done here, but I'm getting a `parent` property scattered throughout each parsed CSS file that's throwing errors on the deep comparisons. Any ideas what's up here?

windows-errors

### CODE REVIEW

**Comment by ai** [comment]
Maybe it is not a good time, because you already finished, but I have different idea :D.

Main problem is that your forget also to fix `gulp cases` task. It is very important to generate this tests automatically. When you change parser, you definatly didn’t want to change every test :).

So my idea is to write some `toJsonForTest(node)` function, which will recursively change object to some state-less state. You can see at `Node#toJSON` as example.

With this function we can fix paths for Windows. And also generate JSON back to files from gulp task, when we will change something in tests.

What do you think about it? (I afraid that I explain idea not in best way :) )

**Comment by jedmao** [comment]
I see what you mean. I think I can do that.

**Comment by jedmao** [comment]
@ai now I understand what `gulp cases` is doing, but I have to think that maybe these test cases shouldn't be pushed to the repo. Instead, it can be a `pre-test` script that generates them, which would pass on any OS w/o modification to the `gulp cases` task. What do you think?

**Comment by ai** [comment]
@jedmao hmmm, nice idea. But for we can store pre-tested data on Travis CI?

**Comment by jedmao** [comment]
We're about to find out (build pending).

**Comment by ai** [comment]
What do you mean?

**Comment by jedmao** [comment]
@ai see the latest commit. Travis is passing. I just deleted all the JSON files and added a `pretest` script in `package.json`. Works like a charm!

**Comment by jedmao** [comment]
Also works on Windows, but you should do what @MoOx suggested and setup AppVeyor for the Windows build.

**Comment by ai** [comment]
@jedmao but how Travis CI will know that it is correct JSON? `pretest` will be runned on same code, that should be tested.

**Comment by jedmao** [comment]
I guess I don't understand when you would build the gulp cases then. Sorry. Not sure what to do here, because I'm not sure why the cases were designed this way.

**Comment by ai** [comment]
@jedmao `cases` is a “reference testing” way. In some point we sure about parser and we make a reference copy of how it must work. Then we just test, that parser still reproduce same output as before.

**Comment by jedmao** [comment]
ok got it.

**Comment by jedmao** [comment]
@ai your strategy is working, but it's super slow! See?

super-slow

**Comment by ai** [comment]
Hm. Strange. Current tests use same way to gerenate object for JSON, convert it to JSON and compare.

I will check code for some performance leaks tomorrow.

**Comment by jedmao** [comment]
I got it to go much faster by including `<case>.windows.json` files for each case.

**Comment by jedmao** [comment]
I'm looking for a better solution though.

**Comment by jedmao** [comment]
There is another option. We could use [path.posix](https://nodejs.org/api/path.html#path_path_posix) for all path operations to keep things Unix-like. Is that a horrible idea?

**Comment by ai** [comment]
Because, I found shorter solution, I took same ideas from this commit on put it under your name to sae your for history: https://github.com/postcss/postcss/commit/b3b49811703eea98b5a5caf8a5e374d6436578aa

**Pull request closed without merging**
