### PR TITLE
Add postcss-current-selector plugin into documentation

### PR DESCRIPTION
**Pull request by komlev**
Add current-selector reference into plugins documentation

### CODE REVIEW

**Comment by ai** [comment]
Can you fix link order (it is by link length), please

**Comment by komlev** [comment]
Done

**Comment by ben-eb** [comment]
You might want to fix this line: https://github.com/komlev/postcss-current-selector/blob/master/index.js#L2

**Comment by komlev** [comment]
Done

**Comment by ben-eb** [comment]
Thanks. :+1:

**Pull request merged**
