### PR TITLE
Add semantic-release for automatic package publishing and save 30 mins on every release

### PR DESCRIPTION
**Pull request by nodkz**
I've added [semantic-release](https://github.com/semantic-release/semantic-release) for automatic package publishing even from the mobile. I heard from talk with @kirjs that it's a pain for you to release a new version.

Come on! 2021 year on the yard and you still waste your time on boring manual publishing procedure. 🤯 I'm using semantic-release for years and it's an amazing tool. I can publish a new version even from the toilet 😜  Also maintainers who able to accept merge requests also will trigger publishing.

I'm using semantic-release in the following repos
- https://github.com/nodkz/mongodb-memory-server
- https://github.com/graphql-compose/graphql-compose

I just need to accept a merge request, and GitHub actions with semantic-release do all boring job:
- compute a new semver according to the last tag in branch & commit prefixes (fix:, feat:, etc.).
- update package version in package.json & do commit
- publish the correctly new package to npm with correct npm tags (no need to publish version 8 after publishing something in v7.x.x). Also you will be able to publish alpha & beta versions.
- write changelog and create release notes (you may improve Release Notes manually after publishing)
- close all related issues and post a message about publishing a new version

For demo purposes, **it now works in DRY RUN mode**. When everything will be tested and logs satisfy you, then `--dry-run` can be removed from `package.json`.

### What neet to do:

- Add tags to the repo with `vN.N.N` format. semantic-release will use these tags for obtaining previous versions
  - [ ] run `git tag v8.3.0 3b86dcb && git push origin v8.3.0`
  - [ ] run `git tag v7.0.35 12832f3 && git push origin v7.0.35`
- [ ] Generate new access token https://www.npmjs.com/settings/ai/tokens
- [ ] Add new secret `NPM_TOKEN` with the obtained token on the previous step https://github.com/postcss/postcss/settings/secrets/actions
- [ ] Force to use [Angular Commit Message Conventions](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-format) with your commit messages
  - all avaliable prefixes you can find in `.releaserc.js` file
  - if some contributor provided wrong commit messages in their PR, just press `Squash & Merge` button which allows you to change the commit message
- [ ] When you will be satisfied by Release workflow logs, remove `--dry-run` flag from `package.json` (**Don't forget to create new tags in repo in `vN.N.N` format**)

### CODE REVIEW

**Comment by ai** [comment]
Is it just copy commit messages to ChangeLog? It is not the best UX for my users.

People write commit messages in context of project internals. In contrast ChangeLig should be written in context of project public API

Just check our current Releases page on GitHub.

Check out how we write ChangeLog for major/minor releases:
https://github.com/postcss/postcss/releases

**Comment by nodkz** [comment]
I don't see a big difference with https://github.com/nodkz/mongodb-memory-server/releases for minor releases. For major releases you able to Edit release message via GitHub UI like this https://github.com/graphql-compose/graphql-compose/releases/tag/v7.9.0.

Anyway, semantic-release enforces you to provide correct commit messages for automatization. Just control commit messages (or fix them via the `squash & merge` button). Then merge changes to `main` or `v7` branch, and the rest boring job will do semantic-release for you. Andrey looks around at other popular repos, most of them use this automatization, but you still are doing this manually. Let bots do the dirty job.

**Comment by ai** [comment]
> Andrey looks around at other popular repos, most of them use this automatization, but you still are doing this manually. 

There are so many mistakes and problems in npm ecosystem. This argument is not valid, because we could copy people mistakes.

**Comment by ai** [comment]
I am closing this PR since it increases the project maintenance complexity rather than solving real issues in the project.

Making commit with ChangeLog is the smallest time consumption.

Most of the time is context switching, tweet preparation.

You are suggesting to spend a few nights of project management migration to make 5 minutes tasks to 2 minutes. These 3 minutes reduction is not a big thing when I spend 10 minutes to find good art for tweet and 10 minutes in tweet text editing.

**Comment by ai** [comment]
BTW, it is a bad example of ChangeLog. It doesn't describe how to migrate and why these changes were made.

https://github.com/nodkz/mongodb-memory-server/releases

**Comment by nodkz** [comment]
As you wish. I just want to make your maintainer life a little bit easier.

Anyway, if you have several mins watch this video from 12:10 https://youtu.be/rCXq86FOlzQ?t=730
There's a small demonstration of how semantic-release works.

**Comment by ai** [comment]
> As you wish. I just want to make your maintainer life a little bit easier.

Saving maintaince time by increasing a maintaince complexity with another popular tool is not the right thing. It is like solving problem in a developer team by adding new team software.

The right thing is hard. You need to analyze process, find real bottleneck and find a solution for that specific bottleneck.

> Anyway, if you have several mins watch this video from 12:10 https://youtu.be/rCXq86FOlzQ?t=730

Video doesn’t answer on real bottleneck. Who will write a Twitter announce? How we can keep git commit messages in projects internals contexts, but keep Changeling in project public API context (ow to migrate, why these changes is important).

Auto-release on PR merge is just a few minutes. It is not a problem to spend them.

The real problem with 7.x branch is support. Issue analyzing when we will have a problem 3 months later. Release planing on big incompatible changes in the future.

**Pull request closed without merging**
