### PR TITLE
add csstyle plugin

### PR DESCRIPTION
**Pull request by geddski**

### CODE REVIEW

**Comment by ai** [comment]
I moved it up (because plugins are ordered by GitHub stars), change name to same as in npm (to add it fast wiith `package` to your `postcss.js`) and make description more clear (all plugins make CSS more maintainable, description must show what your plugin really do).

**Comment by geddski** [comment]
@ai looks good to me. Typo in "woorkflow" though.

**Comment by MoOx** [comment]
Why do you order plugins by stars ? You are going to maintain this list every week ?

**Comment by ai** [comment]
@MoOx when we will add categories, we will order plugins there alphabetical

**Comment by ai** [comment]
@geddski fixed “workflow”

**Comment by geddski** [comment]
Thanks @ai. Killer project btw, keep up the great work.

**Comment by ai** [comment]
Thanks :). BTW, what is the csstyle syntax with PostCSS? Because I think what categry is more relevant for your plugin (see #208).

**Comment by geddski** [comment]
I'll update the site to show it, but for now you can see it in the tests: https://github.com/geddski/csstyle/blob/master/spec/postcss/fixtures/option.pcss

**Comment by ai** [comment]
OK. I will add plugin to “Language extension” until we will have more CSS structure plugins.

**Pull request merged**
