### PR TITLE
accept function for previous map option

### PR DESCRIPTION
**Pull request by montmanu**

### CODE REVIEW

**Comment by ai** [comment]
Want is your user case for this feature?

**Comment by montmanu** [comment]
To dynamically generate the `prev` option's path.. useful when the src file does not already include an annotation and the map is located in a different directory than the src file

**Comment by ai** [comment]
Why you can do something like `{ map: { prev: func() } }`?

**Comment by montmanu** [comment]
I don't think that option currently accepts a function.. that's why I opened this PR and wrote the patch.

**Comment by ai** [comment]
Why you can't execute function on PostCSS#process call? Why you need to call it later inside PostCSS?

**Comment by montmanu** [comment]
I'm not interacting with postcss directly.. I'm interacting with it via a plugin.

**Comment by ai** [comment]
What plugin?

**Comment by montmanu** [comment]
Sorry.. should have mentioned that: grunt-postcss

**Comment by ai** [comment]
I merge it manually in 5.1 branch.

**Comment by montmanu** [comment]
ok, thanks!

**Pull request closed without merging**
