### PR TITLE
Pins nanoid to ^3.3.8

### PR DESCRIPTION
**Pull request by fsmeier**
Infinite loop in nanoid <3.3.8 
See https://github.com/advisories/GHSA-mwcw-c2x4-8c55

### CODE REVIEW

**Comment by fsmeier** [comment]
Heyhey @ai ,
can you please have a look here and also deploy a new tag afterwards? 
Its already updated by you 3 days ago (https://github.com/postcss/postcss/pull/1989) but it would be cool to tag it to resolve the audit messages.

All the best,
Florian

**Comment by ai** [comment]
1. You forgot to update lock file
2. Why do you need to release it? `^` means any version bigger.

**Comment by fsmeier** [comment]
Wow, you react very fast :D thank you!

1. fixed - i thought it was not needed since it was already updated within the lock file; but i was wrong, one line was missing.
2. Currently its only ^3.3.7 which somehow triggers the npm audit for me.

**Comment by fsmeier** [comment]
```bash
netlify-cli@17.38.0
  `-- @netlify/zip-it-and-ship-it@9.41.1
    `-- precinct@11.0.5
      `-- detective-postcss@6.1.3
        `-- postcss@8.4.47
          `-- nanoid@3.3.7
```

**Comment by ai** [comment]
`npm audit` checks not `postxss`, but your `node_modules`.

The issue is in your `node_modules`.

You need to update nested dependencies (there are many tools, I prefer just using `pnpm update`, but for npm you can run `npm audit --fix`).

**Comment by ai** [comment]
I am going to merge it to put your name in to the project history. But I am not going plan to release it since we don’t need it.

**Pull request merged**
