### PR TITLE
[Docs]: Added reference to contributing guidelines

### PR DESCRIPTION
**Pull request by jamesgeorge007**
It is definitely a good idea to provide a reference to the `contributing guidelines` from the docs that people may miss out if otherwise.

### CODE REVIEW

**Comment by ai** [comment]
I didn't add it, because it could be out of context for most of repo visitors.

99% came here to find how to use PostCSS bin their project. In this case “Usage” section is much more important.

Initially I hoped that GitHub will show contribution docs to the users who plan to do contribution in PR UI. Is it stopped to work?

Should we move the link below?

**Comment by jamesgeorge007** [comment]
If someone wishes to contribute to any project the first thing he/she would look out for is the `contributing docs` from which they could get to know regarding the local environment setup and related stuffs. I would say this is definitely worth adding as part of the docs in regard to the previous statement.

**Comment by ai** [comment]
Lens move link below in README

**Comment by jamesgeorge007** [comment]
@ai is this what you intended for?

**Comment by ai** [comment]
Yeap. Thanks :)

**Pull request merged**
