### PR TITLE
Adding postcss-reference to plugin list

### PR DESCRIPTION
**Pull request by dehuszar**

### CODE REVIEW

**Comment by ai** [comment]
Same problem here. I wil add it manually. But next time you should remove your fork and fork `postcss` again.

**Comment by ai** [comment]
Done 48be254

**Comment by ben-eb** [comment]
@ai @dehuszar It helps if you push a PR to a separate branch, rather than `master`, then your PR won't contain unrelated commits.

**Comment by dehuszar** [comment]
Ah. Okay.  No problem.  I'll create a new fork next time.

Thanks!

**Pull request closed without merging**
