### PR TITLE
add postcss-input-style to README

### PR DESCRIPTION
**Pull request by seaneking**
https://github.com/seaneking/postcss-input-style

### CODE REVIEW

**Comment by ai** [comment]
Right now Autoprefixer do this job, but without range and important. Maybe we should thing how to extend it?

**Comment by ai** [comment]
At least, there is a difference between standard `::placeholder` and `::thumb` and `::track`.

**Comment by seaneking** [comment]
Oh really? I had no idea autoprefixer handled this, since there's no non-prefixed standard (that I know of) for the various psuedo-selectors. Is the syntax the same for autoprefixer? 

And re: the !importants and such, not sure if that would fit in autoprefixer's purview, since they're not technically part of prefixing, just fixing cross-browser quirks.

**Comment by ai** [comment]
Only `::placeholder` since it become a standard: https://github.com/postcss/autoprefixer-core/blob/master/test/cases/placeholder.out.css

We can handle `!impoortant` as flexbox props in Autoprefixer.

I think non-standard `::thumb` and `::track` can be in this plugin.

**Comment by seaneking** [comment]
Alrighty let me just strip out `::placeholder` then.

**Comment by seaneking** [comment]
okay that's done, should I change the name of the plugin as well? Seems a bit ambiguous now, if it just handles range inputs. Unless you know of any other inputs with non-standard pseudo selectors this could polyfill?

**Comment by ai** [comment]
Select? Time and date inputs?

**Comment by seaneking** [comment]
Alright, I'll add support for date/datetime. AFAIK <select> has no non-standard pseudo elements, but I'll look into it.

**Comment by ai** [comment]
Cool plugin, BTW :)

**Comment by seaneking** [comment]
Ha thanks. After a bit of digging it seems the only thing accessible on datetime is the text input field itself (as opposed to the actual datepicker), and that's only on webkit. So it seems a bit pointless to add that to the plugin. Might have to just stay a range input polyfill for now :-/

**Comment by ai** [comment]
I think plugin name is good even if it works only with ranges. At least, it is extendable :-D

**Comment by seaneking** [comment]
Yep agreed. I'll keep on the lookout for more to add ;-)

**Pull request merged**
