### PR TITLE
Parse spaces & comments inside important. Fixes #253.

### LINKED ISSUE #253: Doesn't parse excessive whitespace around !important as an important value
This is considered valid CSS in browser:

```css
body {
    color:#000    !     important;
}
```

However when examining the `declaration` it does not have the `important` key.

```
{ type: 'decl',
  parent: 
   { type: 'rule',
     nodes: [ [Circular] ],
     parent: 
      { type: 'root',
        nodes: [Object],
        source: [Object],
        semicolon: false,
        after: '\n',
        lastEach: 18,
        indexes: [Object] },
     source: { start: [Object], input: [Object], end: [Object] },
     before: '',
     between: '',
     selector: 'body',
     semicolon: true,
     after: '\n',
     lastEach: 18,
     indexes: { '18': 0 } },
  source: 
   { start: { line: 2, column: 5 },
     input: 
      { css: 'body {\n    color:#000    !     important;\n}\n',
        safe: false,
        id: '<input css 1>',
        from: '<input css 1>' },
     end: { line: 2, column: 34 } },
  before: '\n    ',
  prop: 'color',
  between: ':',
  value: '#000    !     important' }
```

### PR DESCRIPTION
**Pull request by ben-eb**
So now we can parse a declaration such as this correctly:

```css
h1 {
    color: black      !    /* test comment */   important;
}
```

### CODE REVIEW

**Comment by ai** [comment]
Will not work with :)

```js
a {
  value: important
}
```

But I am very happy, that somebody understand parser :).

**Comment by ben-eb** [comment]
Ah, good catch; what do you think of a `hasToken` method to ensure that the declaration had both `!` and `important`?

Also, if you could help me understand how to unit test it I could cover these cases. :smiley:

**Comment by ai** [comment]
Here is a tests for parser: https://github.com/postcss/postcss/blob/master/test/parse.js#L48

Test compares AST from parsing `test/cases/X.css` with JSON from `test/cases/X.json`.

I suggest you to add new case to [important.css](https://github.com/postcss/postcss/blob/master/test/cases/important.css) and then run `gulp cases`. This Gulp task will all JSON files by CSS AST (like take a snapshot from current parse output AST).

**Comment by ben-eb** [comment]
@ai I've added test cases for this. Any other changes I should make? :smile:

**Comment by ai** [comment]
@ben-eb awesome! But could you also add test for `prop: important`?

**Comment by ben-eb** [comment]
Done. :+1:

**Comment by ai** [comment]
Awesome. It will be OK if I will accept your PR after tuesday? I am very busy on workshop right now :'(

**Comment by ben-eb** [comment]
Of course! Will just squash the history down. :smile:

**Pull request merged**
