### PR TITLE
Optimize and idiomantify tokenizer

### PR DESCRIPTION
**Pull request by vanesyan**
Some style correction, and handwrite char codes

### CODE REVIEW

**Comment by ai** [comment]
Yeap, seems like good thing :)

**Comment by ai** [comment]
I will check it in weekend and maybe take a benchmarks result (does browsers works with const in different way?).

**Comment by vanesyan** [comment]
In theory it should works faster, than with `let` keyword, because VM knows that the const variable will not change and size of it never change.

**Comment by ai** [comment]
Babel compiled `const` to `var` so we can’t see changes right now :)

**Pull request merged**
