### PR TITLE
Proposed edits for first 175 lines

### PR DESCRIPTION
**Pull request by davidtheclark**
I just read the first 175 lines tonight and proposed changes. I also have a few questions:

- Have you thought about documenting more specifics about parameters, e.g. expected types, whether they're optional or not, and defaults? That information is generally useful.

- I'm not certain whether my change at line 131 is fully accurate --- please have a look (presumably you'll look at all the changes.)

Nice job @ai. If you think this was useful I will look at the rest of the doc next chance I have! If there's anything you'd like me to do differently, just let me know.

### CODE REVIEW

**Comment by lydell** [comment]
Nice job! :+1

**Comment by ai** [comment]
@davidtheclark thank. It was awesome work.

Yes, you are right about 131 line. But it is not about `return undefined` but about no `return` statement at all. I fixed it.

**Comment by davidtheclark** [comment]
Cool. I'll do the same for the rest sometime this weekend, probably.

**Comment by ai** [comment]
@davidtheclark I really need your help for new `README.md`. I didn’t happy about some constructions, but README.md is much difficult that `API.md`. And  it is much important for PostCSS future.

https://github.com/postcss/postcss/blob/master/README.md

**Comment by davidtheclark** [comment]
Ok. I will help after i finish the API docs.

**Pull request merged**
