### PR TITLE
Added postcss-property-shorthand to plugins.md

### PR DESCRIPTION
**Pull request by alanev**
https://github.com/alanev/postcss-property-shorthand

### CODE REVIEW

**Comment by ai** [comment]
Does current input/output example is correct in plugin’s README? I miss how it works.

**Comment by alanev** [comment]
Added better examples

**Comment by alanev** [comment]
Idea for plugin is from ES2015 feature - property shorthand
http://es6-features.org/#PropertyShorthand

**Comment by ai** [comment]
Honestly, it looks very weird. Do you use it in production with other developers?

**Comment by alanev** [comment]
Yes, I do. It is useful plugin for me. It helps me to develop faster.

**Comment by ai** [comment]
I afraid that this plugin will promote PostCSS as a tool with weird unmaintable syntax 😔

If you don't know about this plugin before, you will not be able to understand syntax.

**Comment by ai** [comment]
You could add plugin to postcss.parts. Plugins here is more like recommended plugins.

**Comment by alanev** [comment]
Well. Thanks

**Comment by ai** [comment]
C`mon, you see that so many people complains about this problem. Especially in Russian Internet.

**Pull request closed without merging**
