### PR TITLE
implemented unique node id

### PR DESCRIPTION
**Pull request by delorge**
solution for #790

### CODE REVIEW

**Comment by ai** [comment]
1. I released `postcss-parser-test`, please add it.
2. Don’t broke indentation ;).

**Comment by delorge** [comment]
investigating problems with last commit, I can confirm that `postcss-parser-test` has nothing to do with toJSON() node method, so I decided to change appropriate tests. @ai could you please check them out?

**Comment by delorge** [comment]
so what will we do about this one? toJSON method isn't really about cleaning node itself but its parent.

**Comment by ai** [comment]
I will look on next week. Anyway we need to finish JSDoc.

**Comment by delorge** [comment]
okay then :)

**Pull request merged**
