### PR TITLE
Adding postcss-extract-value

### PR DESCRIPTION
**Pull request by lutien**

### CODE REVIEW

**Comment by ai** [comment]
Be careful — always use origin sorting :). Here is ABC sorting, but `postcss-` prefixed plugins is in the top (good naming promotion)

**Comment by ai** [comment]
Also you forget to add URL for your link (they are ordered by length)

**Comment by ai** [comment]
I will close this PR, anyway it will be better to send other one

**Comment by lutien** [comment]
There are some mistakes in sorting in section "Others" and this confused me :(

**Pull request closed without merging**
