### PR TITLE
use the system eol setting

### PR DESCRIPTION
**Pull request by DanielRuf**
this fixes the failing unit tests of postcss-cssnext on Windows

### CODE REVIEW

**Comment by ai** [comment]
Oh, this changes could be done only in the major update. Maybe we should use some option in `toString()`?

**Comment by ai** [comment]
What is the real problem for you here? Maybe I can find a solution without breaking changes?

**Comment by DanielRuf** [comment]
The problem is that the testsuite of postcss-cssnext produces 3 failing tests, two of them are because of the line ending settings which are forced to `\n` by postcss (by default).

**Comment by ai** [comment]
There are many ways to solve `postcss-cssnext` issue :). Changing EOL will break tests in *many* projects :(.

**Comment by DanielRuf** [comment]
Hm, but the testfiles automatically get the system file endings and the generated ones use `\n` even on my Windows machine.

Or is some options value needed that the maintainer has to set in the testsuite?

**Comment by ai** [comment]
> testfiles automatically get the system file endings

I think they just don’t test is on Windows. It is better to fix testfiles.

But I like you fix. I will keep it until 7.0 release (I can’t release too many major updates in the year).

**Comment by DanielRuf** [comment]
I guess there is no consequent and uniform decision abroad the postcss plugins. At least there are different settings and setups (some have appveyor and travis and many do not).

**Comment by DanielRuf** [comment]
> But I like you fix. I will keep it until 7.0 release (I can’t release too many major updates in the year).

So should I keep this open for the future and reference here from postcss-cssnext?

**Comment by ai** [comment]
> So should I keep this open for the future

Yeap :) It is a good idea for 7.0.

**Comment by gucong3000** [comment]
I ‘d like to see a software output same result on any platform

**Comment by DanielRuf** [comment]
> I ‘d like to see a software output same result on any platform

Well, Windows changes the line endings so the testsuite breaks there. It is a fact that the testsuite is failing when you run it on Windows at the moment. The systems use different line endings when they generate files. So this should be solved by this PR.

Not sure why the downvote as I try to fix an actual issue and make it more independent.

**Comment by gucong3000** [comment]
> Windows changes the line endings
Windows will do any thing for line endings, Maybe your `git` did it.

try this:
```bash
git config --global core.autocrlf input
```

**Comment by DanielRuf** [comment]
Tests should be independent and no specific line ending be required in general.

Also setting this globally is not what the default is and as I already wrote, it is the file generation while running the testsuite, this has nothing to do with the Git config in general.

And it should not require such specific settings.

Many also include the tests in own projects but do not need a Git setup.

There is a reason for `eol` constants in many languages ;-)

And I guess @ai as owner can decide what makes sense and what not. Also this change does not negatively affect you directly. Or do you face any specific issues with the proposed change?

**Comment by DanielRuf** [comment]
Mixed line endings would otherwise create other issues imo.

**Comment by gucong3000** [comment]
Maybe we should keep EOL as file is. Just like IDEs and editors.

**Comment by ai** [comment]
Sorry, I decided to use only `\n` on every platform because of:

1. Different new lines will make tests much more complex (some most of plugins compare output string).
2. Even Microsoft Notepad now supports UNIX new lines.

I can change my mind if you will show some good practical reasons.

And I send you a hug. I know how it is sad when somebody reject your PR. Your code is great and idea is interesting.

**Pull request closed without merging**
