### PR TITLE
Better view parser errors.

### PR DESCRIPTION
**Pull request by h0tc0d3**
I have a previous clean clone of the repository and can't pass parser test in the box.
It threw an error in 40k lines. The log was very big and it was not clear where the error.
The error was in one character, which was deleted \r. This code will help you to easily find errors in large text.

### CODE REVIEW

**Comment by ai** [comment]
Can you show current diff vs. new diff?

**Comment by h0tc0d3** [comment]
Of corse. 
my
old

**Comment by ai** [comment]
You missed built-in diff in Jest. Jest shows it after `expected` and `received`. It shows changes pretty well.

I moved to Jest especially because of awesome diffs.

ruzoztn

**Comment by h0tc0d3** [comment]
it's excellent!
> Jest shows it after expected and received
Expected and received can be very big. I think they need to be hidden. Throwing a log in 40k lines is a bad.
The console buffer will not be able to put this all the text.

**Pull request closed without merging**
