### PR TITLE
Only include the library directory to reduce npm package size

### PR DESCRIPTION
**Pull request by Siilwyn**
Decrease size of the postcss npm package by 57% (295 kB) by only including the library directory. Instead of ignoring a bunch files I included the library directory in the package.json.

### CODE REVIEW

**Comment by ai** [comment]
Em, what about docs and type definitions? They are very useful for developers

**Comment by Siilwyn** [comment]
I don't think much people go into the *node_modules* directory, open *postcss* and then read the docs offline. I could be wrong so if anybody is against removing the docs from the packaged version of postcss, speak up.
Though for anybody wanting to read the docs offline cloning this repository would a good option. Also the readme file is included which contains some examples of how to use postcss.

**Comment by ben-eb** [comment]
I read docs offline. It's much easier than *opening a browser*, searching for the *repository*, and using the *web UI* to find the relevant file. I can do it all from `node_modules` using Atom.

**Comment by TrySound** [comment]
@Siilwyn That's why readme.md can't be ignored in npm.

**Comment by Siilwyn** [comment]
@TrySound exactly, I think the readme.md is enough for most people.

**Comment by TrySound** [comment]
@Siilwyn readme is docs. postcss has more docs than only readme. So you should include it.

**Comment by Siilwyn** [comment]
In hindsight, and after all of your replies (which I thank you for) I see why this isn't such a good idea. I still don't fancy the idea of including the TypeScript source but I understand why it is included.

:outbox_tray:

**Comment by TrySound** [comment]
We too don't like typescript, but it is.

**Comment by ai** [comment]
Also I am big fan of airplane development (because you have Internet for procastinate). It is one of the main reasons for me for offline docs :D.

**Pull request closed without merging**
