### PR TITLE
Add postcss-safe-important plugin

### PR DESCRIPTION
**Pull request by Crimx**
A configurable plugin that adds !important to style declarations safely.

### CODE REVIEW

**Comment by ai** [comment]
Why this plugin can be useful for other developers? On first look it is just a custom in-app plugin.

**Comment by Crimx** [comment]
@ai [This](http://cleanslatecss.com/#Why-would-I-need-it) might explain why. it's also useful to extension content script injection.

**Comment by ai** [comment]
So you should fix a docs to make it more clear ;)

**Comment by Crimx** [comment]
Done. Thank you for being patient and do excuse my poor English. Feel free to point out anything I've done wrong :).

**Comment by ai** [comment]
Awesome. Second fix: can you put your plugin and its link in right order (abc order in plugins, with `postcss-` on top and size order in links)

**Comment by ben-eb** [comment]
Thanks for your contribution. :+1:

https://github.com/postcss/postcss/commit/294c793f72ada0daf8ca56dc4c4c0c3048d8a5f7

**Pull request closed without merging**
