### PR TITLE
Fixed broken link to postcss-url in README.md

### PR DESCRIPTION
**Pull request by simplesmiler**

### CODE REVIEW

**Comment by simplesmiler** [comment]
@ai looks like the `t` in `postcss-urlt` was from `cssfmt`, which is missing a `t` from the end.
https://github.com/postcss/postcss/blame/master/README.md#L596

**Comment by ai** [comment]
@simplesmiler yeap, can you send second PR

**Comment by simplesmiler** [comment]
@ai sure.

**Comment by simplesmiler** [comment]
@ai never done this before, should I rebase my patch branch against master first?

**Comment by ai** [comment]
The better wway if to remove your fork an then fork project again

**Comment by simplesmiler** [comment]
@ai  #499

**Pull request merged**
