### PR TITLE
Files Refactored

### PR DESCRIPTION
**Pull request by gkal19**
- Files *.es6 in ./lib 👌 
- Files *.js in /test 👌

### CODE REVIEW

**Comment by ai** [comment]
It is the worse time to send so big PR 😅 Current development branch is `orias` and we plan to release it in next few days.

**Comment by ai** [comment]
Also, note that PostCSS should works in IE 11

**Comment by h0tc0d3** [comment]
I think a bad idea in this refactoring. Especially in the tokenizer. This may affect the performance degradation. Replace strings with es6 template string don't make weather.

**Comment by gkal19** [comment]
I understood :cry:

**Comment by ben-eb** [comment]
`Array.prototype.includes` isn't supported until Node 6, not the best idea to get rid of it. 😄

**Comment by h0tc0d3** [comment]
Benchmark on Node 7.9.0:
```
1:
Name: .includes         Time: 1.7182436487297459ms.             Full Time: 17179ms.             Result: 46330732
Name: indexOf           Time: 1.5642128425685138ms.             Full Time: 15639ms.             Result: 46330732
2:
Name: .includes         Time: 1.6923384676935387ms.             Full Time: 16920ms.             Result: 46330732
Name: indexOf           Time: 1.616123224644929ms.              Full Time: 16158ms.             Result: 46330732
3:
Name: .includes         Time: 1.6825365073014602ms.             Full Time: 16822ms.             Result: 46330732
Name: indexOf           Time: 1.5832166433286656ms.             Full Time: 15829ms.             Result: 46330732
```

**Comment by ai** [comment]
@gkal19 I move few changes of your PR in `orias` branch, so you will be in history :)
https://github.com/postcss/postcss/commit/29a51b9c82bdf11f226e0d4196d18865d4bd10de

Also if you live in Rio, I could bring you Russian candy when I will be in Brazil this summer.

**Comment by ai** [comment]
Good practice for big refactoring PR — before PR create small issue with your plan for maintainer approve.

But you are very productive, nice that you clean so many files :).

**Comment by gkal19** [comment]
@ai 
Thanks! Unfortunately, I do not live in Rio: laugh:

**Pull request closed without merging**
