### PR TITLE
Add new plugin to Fun section

### PR DESCRIPTION
**Pull request by Hugoer**

### CODE REVIEW

**Review by nucliweb — APPROVED** [review]
👏🏼

**Comment by ai** [comment]
Looks awesome!

**Comment by ai** [comment]
I scheduled a tweet to promote your plugin in `@postcss`. Am I right that it is your Twitter account https://twitter.com/Hugoerdev ?

**Comment by Hugoer** [comment]
Great!! Yes it is correct. I would be very happy if postcss account send a
Twit about this plugin. Thanks!

**Pull request merged**
