### PR TITLE
Add postcss-selector-prefixer plugin

### PR DESCRIPTION
**Pull request by ronnyamarante**
Add postcss-selector-prefixer plugin - adds a prefix to css selectors.

### CODE REVIEW

**Comment by TrySound** [comment]
@ronnyamarante Any difference from this?
https://github.com/thompsongl/postcss-class-prefix

**Comment by ai** [comment]
Looks like totally similar.

**Comment by ronnyamarante** [comment]
This works only with classes, please look at my [tests](https://github.com/ronnyamarante/postcss-selector-prefixer/blob/master/test.js). Thanks:)

**Comment by ronnyamarante** [comment]
Thank you! :+1:  
Have any problem or conflcit with merge? I dont see in plugin list.

**Comment by ai** [comment]
@ronnyamarante very strange :-/

Can remove your copy of `postcss` repo. Fork it again and send new PR.

BTW, also could you fix a order of your plugin. Links are ordered by length.

**Pull request merged**
