### PR TITLE
Add postcss-ant to list of plugins

### PR DESCRIPTION
**Pull request by corysimmons**

### CODE REVIEW

**Comment by ai** [comment]
We need better description. Right now it tells about features for developers. But we need to describe a benefits for users. Why they should take care about “autosizes and more”?

**Comment by corysimmons** [comment]
tbh, I've never been sure how to describe it in a vague enough way to cover all its use-cases that won't take a paragraph.

"Returns any size you could ever need in any situation" ?

**Comment by ai** [comment]
Why users even need some size? ;) What use cases?

**Comment by corysimmons** [comment]
Why do users need precise "sizes" in design-oriented CSS?

Grid widths. Positioning elements precisely.

**Pull request closed without merging**
