### PR TITLE
add postcss-image-set-polyfill to plugins list

### PR DESCRIPTION
**Pull request by SuperOl3g**
Hi there!
I've made a small css func polyfill, hope somebody will find it very useful. 
So I propose add it to plugins list.

### CODE REVIEW

**Comment by ai** [comment]
What is different with [postcss-image-set](https://github.com/alex499/postcss-image-set)?

**Comment by SuperOl3g** [comment]
[alex499 version](https://github.com/alex499/postcss-image-set) just fallback to first image for all no-support browsers.
My version fully simulate `image-set` function logic.

**Comment by ai** [comment]
Wow, great!

**Comment by SuperOl3g** [comment]
Thanks)

**Pull request merged**
