### PR TITLE
Added finally method to LazyResult

### PR DESCRIPTION
**Pull request by igorkamyshev**
I try to resolve issue #1146.

Please, review my PR and give me feedback.

### CODE REVIEW

**Comment by ai** [comment]
You forgot about test 😏

**Comment by igorkamyshev** [comment]
@ai sure. I must write tests only for `finally` or for `then` and `catch` too?

**Comment by ai** [comment]
I think I cover `then` and `catch` 😅

**Comment by igorkamyshev** [comment]
@ai okay. Will be fixed! 👨🏻‍💻

**Comment by igorkamyshev** [comment]
Added test for `finally`.

Please, tell me, in which file I may see your tests for `then` and `catch` for inspiration?

**Comment by ai** [comment]
Great. But this test doesn't test that callback was really executed 😏.

Also you must return a Promise from any tests with late execution (any test with Promises).

Check other tests for examples. Or google `jest test promise`.

**Comment by igorkamyshev** [comment]
I fixed test.

But, I guess on CI test will be failed anyway, because `Promise#finally` available only in Node.js 10+.

**Comment by ai** [comment]
Your have a problems on Travis CI

**Comment by ai** [comment]
`Promise#finally` is just a syntax sugar. Just user old methods for it.

**Comment by igorkamyshev** [comment]
Done.

**Comment by ai** [comment]
Released in 7.0. Thanks

**Pull request merged**
