### PR TITLE
tests: use npm ci

### PR DESCRIPTION
**Pull request by DanielRuf**
`npm ci` is much faster and is meant for CI. This PR is meant for evaluating the new ci command and testig the performance and compare the logs of Travis CI.

https://docs.npmjs.com/cli/ci
http://blog.npmjs.org/post/171556855892/introducing-npm-ci-for-faster-more-reliable

### CODE REVIEW

**Comment by ai** [comment]
Hi. Thanks for PR.

But I have a question. Why we need to use `npm ci` if we already use `yarn`?

**Comment by DanielRuf** [comment]
I'll check tomorrow if the changes makes much sense and how much it would improve thr builds.

**Comment by ai** [comment]
Yarn is a alternative for npm. So we don't call npm at all. We use only yarn.

I really recommend to look to yarn as well. It is faster than npm, API is better and team work better.

**Comment by DanielRuf** [comment]
> I really recommend to look to yarn as well. It is faster than npm, API is better and team work better.

The npm team learned from them and improved npm 5 and 6 and they are not interchangeable (lockfiles, tools, ecosystem, ...). But thanks for the recommendation (we do not prefer lockins / changes here).

**Comment by ai** [comment]
So you know about the Yarn 😊

What is the point to installing npm in this case? Also what is a point in installing `grunt-cli`? PostCSS uses Gulp.

**Comment by DanielRuf** [comment]
The grunt-cli seems to be by accident, sorry,

**Pull request closed without merging**
