### PR TITLE
Added postcss-esplit plugin

### PR DESCRIPTION
**Pull request by VitaliyR**
Hello. I've created and polished [postcss-esplit](http://github.com/vitaliyr/postcss-esplit) plugin - and decided to add it to readme. 

The idea inside it that we were used in our project blesscss tool which just doing the same job. But it doesn't have support for source maps. Also we though to move our project to use postcss so I decided to wrote a plugin for postcss which would do just the same thing blesscss doing but with support of sourcemaps.

What do you think?

### CODE REVIEW

**Comment by ai** [comment]
IE 9 support is not so popular, sorry

**Comment by VitaliyR** [comment]
@ai say it to Chinese coders :)

**Comment by ai** [comment]
We have a long fallback plugins list in special file https://github.com/postcss/postcss/blob/master/docs/plugins.md#fallbacks

README.md now containing highlighted plugins

**Comment by VitaliyR** [comment]
@ai should I add it there?

**Comment by ai** [comment]
Yeap

**Comment by VitaliyR** [comment]
@ai 👍

**Pull request closed without merging**
