### PR TITLE
Add postcss-not-x-child plugin to the plugins list

### PR DESCRIPTION
**Pull request by hudochenkov**
Add [postcss-not-x-child](https://github.com/hudochenkov/postcss-not-x-child) plugin to the plugins list.

### CODE REVIEW

**Comment by ai** [comment]
What is a reason for this plugin? WHy we can’t write `div:not(:first-child)`?

**Comment by hudochenkov** [comment]
I've use a lot of `div:not(:first-child)` and `div:not(:last-child)` after [this advice](https://github.com/AllThingsSmitty/css-protips#use-not-to-applyunapply-borders-on-navigation) recently. These selectors looks a little messy. So I propose `:not-first-child` and `:not-last-child` shortcuts as better looking selectors and with improved readability.

**Comment by hudochenkov** [comment]
Frankly I don't know if someone else will need these plugin. I was just thinking that every PostCSS plugin should be listed in that list.

**Comment by ai** [comment]
Nope, I I think to that it is one-user plugin :). Maybe you even should not use, because it do not brings you any benefits, just confuse other developer.

I try avoid dangerous plugins from this list ;).

**Comment by hudochenkov** [comment]
No problem. Thank you for constantly keeping PostCSS ecosystem and community on the right path :)

P. S. It was my first plugin and npm package ever, so it was a great experience for future development :)

**Pull request closed without merging**
