### PR TITLE
Add postcss-inline-comment

### PR DESCRIPTION
**Pull request by moczolaszlo**
It's only removes the declaration, which starts with '//'.

### CODE REVIEW

**Comment by ai** [comment]
Nice hack! :D

PostCSS 4.2 will have custom parsers. It will be a better solution.

I thinking that we should not include temporary hacks to Plugins list.

**Comment by moczolaszlo** [comment]
Ok, not problem.
I just made it, because it's very useful for me NOW. :D

**Comment by ai** [comment]
@moczolaszlo I will post about it in PostCSS twitter account

**Comment by moczolaszlo** [comment]
Thank you! ;)

**Comment by ai** [comment]
@moczolaszlo do yo have twitter account?

**Comment by moczolaszlo** [comment]
@ai No, I don't.

**Comment by kukac7** [comment]
:+1:

**Comment by lydell** [comment]
I felt like learning a bit about streams and buffers today, so I played with making a streaming program that strips singleline comments from CSS. I thought you might be interested :) [strip-css-singleline-comments](https://github.com/lydell/strip-css-singleline-comments)

**Pull request closed without merging**
