### PR TITLE
Add postcss-map-url

### PR DESCRIPTION
**Pull request by simonsmith**
Port of [rework-plugin-url](https://github.com/reworkcss/rework-plugin-url) to PostCSS

https://github.com/simonsmith/postcss-map-url

Noticed you've merged the `4.1` branch so have chosen `master` for this PR

### CODE REVIEW

**Comment by MoOx** [comment]
Do you know that postcss-url already provide this feature ?

**Comment by simonsmith** [comment]
I didn't know you could no. It allows you to alter the original `url` and return a modified version?

**Comment by simonsmith** [comment]
Ah I see, you can pass it a function as well?

In that case maybe this PR should be reverted..?

**Comment by ai** [comment]
NP, i revert it

**Comment by simonsmith** [comment]
Thanks, apologies

**Pull request merged**
