### PR TITLE
Add postcss-utilities

### PR DESCRIPTION
**Pull request by ismamz**
I've added it into "Packs", but perhaps we could also add into "Shorcuts".

### CODE REVIEW

**Comment by ai** [comment]
Oops, I missed this PR by some reason :(

**Comment by ai** [comment]
Don’t forget to send PR to https://github.com/himynameisdave/postcss-plugins#submitting-a-new-plugin

**Comment by ai** [comment]
I also added your plugin to main highlighted list 6d6f33a

**Comment by ismamz** [comment]
I delayed send to improve the docs. I've added to postcss-plugins already :+1:

**Pull request merged**
