### PR TITLE
[WIP] Updating current parser to support tokens streaming

### PR DESCRIPTION
**Pull request by hzlmn**
As discussed @ai .

I am facing issues while running local tests for parser (tokenizer is ok). I've wasted much time to figure out what can cause it, and then clone fresh master `postcss` and seems like lots of tests for parser failing without any actions from my side. Am I doing something wrong?

Also some test cases for [postcss-parser-tests](https://github.com/postcss/postcss-parser-tests/tree/master/cases) like [this](https://github.com/postcss/postcss-parser-tests/blob/master/cases/escape.css) for example failed while them expacted not to throw any exception.

Also I created [decoupled tokenizer](https://github.com/hzlmn/postcss-tokenize), a little more structural, that could be useful for building additional parsers for `postcss` for example.

**Roadmap**
  - [x] Update tokenizer
  - [x] Update parser to work with tokens
  - [x] Check performance compatibility

### CODE REVIEW

**Comment by ai** [comment]
I will go to trip this Friday. Please, ping again in Saturday. I will look.

**Comment by hzlmn** [comment]
ok

**Comment by hzlmn** [comment]
Seems like [this](https://github.com/postcss/postcss-parser-tests/blob/master/cases/escape.css) test case does't pass tokenizing step. I am really wondering why it's not failed inside build, but here is sample.

```js
var tokenize = require('./lib/tokenize')
var Input = require('./lib/input')


var css = `
a {
    background: url("a).png");
    background: url(a;a);
    background: url(a/*);
    background: \;a;
}

:not([foo=")"]) { }
:not(div/*)*/) { }
:not(:nth-child(2n of [foo=")"])) { }
[foo=\"] { }
[foo=\{] { }
[foo=\(] { }
[foo=yes\:\(it\'s\ work\)] { }

\@noat { }

h1\\{
    color: \\;
}

[attr=;] { }
`

var input = new Input(css, {})
var tokens = tokenize(input)

console.log(tokens)

```

and with current master `postcss` I have

```shell

/home/olehkuchuk/Projects/postcss/lib/tokenize.js:57
        throw input.error('Unclosed ' + what, line, pos - offset);
        ^
CssSyntaxError: <css input>:12:6: Unclosed string
    at Input.error (/home/olehkuchuk/Projects/postcss/lib/input.js:113:22)
    at unclosed (/home/olehkuchuk/Projects/postcss/lib/tokenize.js:57:21)
    at tokenize (/home/olehkuchuk/Projects/postcss/lib/tokenize.js:167:29)
    at Object.<anonymous> (/home/olehkuchuk/Projects/postcss/index.js:31:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)

```

**Comment by ai** [comment]
@hzlmn you put CSS file content to backticks string (<code>`</code>), but forget about `\`.

```
`\'` //=> "'"
```

So if you move CSS file content to string, you need to replace `\` to `\\`.

**Comment by ai** [comment]
Even if this PR is not finished, it is really amazing than you did so much work.

I don’t expect any PR in parsers — most of developers afraid even change a single line in parser/tokenizer. And then you make so big changes in such small time :D.

**Comment by hzlmn** [comment]
@ai Correct, my bad :) 
Current version passed all tests correctly, but updated version not. All `tokenizer` related test passed, but `escape.css` tokenization fails with above error. I Will look more closely on it.

**Comment by ai** [comment]
Seems like tests passed. Is it finished? We could release it in 6.0.

**Comment by hzlmn** [comment]
@ai Not yet, I will ping you when it is ready.

**Comment by ai** [comment]
Don’t forget to run `postcss-benchmark`. It could compare local `postcss` if they are both in same parent dir and you compile PostCSS by `gulp build`.

```
Dev/
  postcss/
    build/
    …
  postcss-benchmark/
```

**Comment by hzlmn** [comment]
What `postcss-benchmark` do you mean? [This](https://github.com/postcss/benchmark) one  ?

**Comment by ai** [comment]
@hzlmn yeap

**Comment by hzlmn** [comment]
@ai Hi, small question - why [this](https://github.com/postcss/postcss-parser-tests/blob/master/cases/inside.json#L23-L32) node has no `end` block ? Is it a bug, or there are some purposes?

**Comment by ai** [comment]
@hzlmn looks like bug

**Comment by hzlmn** [comment]
@ai Will you fix it, or can I ? I mean updating test case to be proper.

**Comment by ai** [comment]
@hzlmn if you will fix it, it will be awesome :D. We will have a major release for it anyway.

**Comment by hzlmn** [comment]
@ai It is already fixed, I just have 6 failing tests and this PR will be finished in 2-3 days (Depends on how much coffee I will drink :) )

**Comment by hzlmn** [comment]
@ai I passed all tests except [that](https://github.com/postcss/postcss-parser-tests/blob/master/cases/inside.json#L23-L32) one, but `postcss-benchmark` shows almost the same results :confused: I think it's because [buffering](https://github.com/postcss/postcss/pull/953/files#diff-ad62f7b95d7ad1a11fc55ad6a744b3dbR110) for jumping back from current position. I will try to improve it a bit.

**Comment by ai** [comment]
@hzlmn same benchmark is good too. We use less memory without a reduce of CPU speed. So it is a great step anyway.

**Comment by ai** [comment]
But any improving is good idea :).

Be ready that we need few weeks to release 6.0. I need to change few other things if we are going to major release.

**Comment by hzlmn** [comment]
@ai Yes, but it is less than I expected :pensive:

**Comment by ben-eb** [comment]
If it's backwards compatible with the 5.0 tokenizer then we can do a minor if you like. But I think it's better to be safe and release it as a major, it protects our users from potential unforeseen breaking changes.

**Comment by hzlmn** [comment]
@ai When do you plan a release? I am playing a bit with different structures and try to add performance improvement ...

**Comment by ai** [comment]
I am waiting for you to merge it. And then I will need few weeks to fix `raws` issue

**Comment by ai** [comment]
Do you want to add something more to this PR?

**Comment by hzlmn** [comment]
@ai Of course, I am working on it. Currently, when updated to new architecture (that should improve performance a bit) I have 3 tests failing and Im working on resolving them.

Also I have problem with `ava` when I use it directly without `gulp` task https://github.com/avajs/ava/issues/1211 maybe you had similar problem.

**Comment by ai** [comment]
Nope, sorry. But you can run AVA by CLI without Gulp. For example, you can use my `n` alias 
https://github.com/ai/environment/blob/master/zshrc#L52

**Comment by ai** [comment]
We plan to start 6.0 branch tomorrow. Do you have anything to add?

**Comment by ai** [comment]
I merged it to 6.0 branch manually. If you want to tune it more, please send other PR to `orias` branch.

**Comment by ai** [comment]
Seems like you didn’t use stream tokenizer in this PR? 

```js
let tokens = tokenizer(new Input(css), { ignoreErrors: true }).tokenize();
```

This could be a reason for same benchmark results.

**Comment by ai** [comment]
technically current tokenizer is 10% slower and have no streaming support (use same memory).

@hzlmn you should told me that. It is good, that I accidentally find it.

**Comment by ai** [comment]
I finished your work: 1427538

Not it is totally streamed and have same performance.

**Comment by hzlmn** [comment]
Thanks. It's almost same that I done [here](https://github.com/hzlmn/postcss/blob/fork1/lib/parser.es6), just wanted to improve perf at bit, but seems like in current scope it is pretty tricky.

**Pull request closed without merging**
