### PR TITLE
Fixed selector parsing with comment inside

### PR DESCRIPTION
**Pull request by hzlmn**
Fixes https://github.com/postcss/postcss/issues/1066 . 

As was discussed, if comment does not have at least space from one of side interp it as a part of word.

> Note,  some of `postcss-parser-tests` should be updated as them match old parsing rules.

### CODE REVIEW

**Comment by hzlmn** [comment]
All passed except one for `:not(div/*)*/)`. What should parser produce in such case?

**Comment by ai** [comment]
@hzlmn same as before `:not(div)`. Otherwise, this PR will break API.

**Comment by hzlmn** [comment]
@ai So comment stripping should be performed for all selectors types except class, id or type or when it should be stripped and when not? Don't you find it a bit confusing that certain selectors will be parsed differently like if i get `.Compo/*test*/nent` as a selector value i expect  parsing`.a/*test*/[href*="test"]` to get the same.

**Comment by ai** [comment]
Let's keep comments only inside identificator (letters and digits). Not between difficult like different tokens.

**Comment by ai** [comment]
Released in 6.0.17

**Pull request merged**
