### PR TITLE
Add assign method to Nodes

### PR DESCRIPTION
**Pull request by jonathantneal**
This PR adds an `assign` method to all nodes, allowing authors to assign multiple properties to a node from a single object.

```js
decl.assign({ prop: 'word-wrap', value: 'break-word' })
```

This can improve code clarity when updating multiple properties while offering a helpful typing experience.

### CODE REVIEW

**Comment by ai** [comment]
Looks nice. Just fix CI and I will release it in minor in a next month.

**Comment by jonathantneal** [comment]
Thanks, @ai. Fixed.

**Comment by ai** [comment]
8.3 will be released when https://github.com/postcss/postcss/pull/1582 will be ready

**Comment by ai** [comment]
Thanks. Released in [8.3](https://github.com/postcss/postcss/releases/tag/8.3.0).

**Pull request merged**
