### PR TITLE
add postcss-foreach plugin

### PR DESCRIPTION
**Pull request by verybigman**

### CODE REVIEW

**Comment by ai** [comment]
What is a difference with postcss-for and postcss-foreach?

**Comment by verybigman** [comment]
It get val and iterator into the loop

**Comment by ai** [comment]
Same as postcss-each.

**Comment by ai** [comment]
@verybigman I think you should remove this repo, because [postcss-each](https://github.com/outpunk/postcss-each) already do it.

**Comment by verybigman** [comment]
Give me example, please
Вт, 30 июня 2015 г. в 21:51, Andrey Sitnik <notifications@github.com>:

**Comment by ai** [comment]
postcss-each plugin CSS:

```css
@each $icon in foo, bar, baz {
  .icon-$(icon) {
    background: url('icons/$(icon).png');
  }
}
```

**Comment by ai** [comment]
@verybigman you already fork postcss-each. Why? WHy not PR to postcss-each?

**Comment by verybigman** [comment]
@ai where in your example index of loop? I fork because create another iterator. for, each, foreach. This is problem? I can create pr to the postcss-each. You really think is right?

**Comment by ai** [comment]
Yes, you should send PR to postcss-each and make a fork only if postcss-each forbid your PR.

**Comment by verybigman** [comment]
Ok, no problem!

**Comment by verybigman** [comment]
Wait https://github.com/outpunk/postcss-each/pull/3

**Pull request closed without merging**
