### PR TITLE
add postcss setup instructions for webpack 2

### PR DESCRIPTION
**Pull request by hidace**
I was able to get post-css working with Webpack 2 using this simple configuration (however, wasn't able to get post-css and webpack 2 working with the original instructions for webpack). 
Please feel free to confirm. Thanks!

### CODE REVIEW

**Comment by ai** [comment]
LoaderOptionsPlugin is a hack for old loader compatibly. postcss-loader has a native support without a hacks. Check loader docs.

But I agree that we need to update docs to webpack 2. Will you fix your PR?

**Comment by hidace** [comment]
Oh, great - good to know. Yeah, will take a look and update. Thanks!!

**Comment by michael-ciniawsky** [comment]
@ai New docs WIP is [here](https://github.com/michael-ciniawsky/postcss-loader/tree/docs) I try to uoate soon, e.g an `ExtractTextPlugin`example is missing, sry I was busy the last weeks 😛  @hidace You can take what you like from there + please add an `ExtractTextPlugin` example and send PR to @postcss-loader if you're faster :), I need to finish `vue-loader` PostCSS [implementation](https://github.com/vuejs/vue-loader/commit/9b65ed19f3c3f43c7b51b2557fe6677566404c83) update beforehand

**Comment by ai** [comment]
@hidace any updates?

**Pull request merged**
