### PR TITLE
Only show to/from deprecation notice once per instance

### LINKED ISSUE #272: Please show depreciations notice once per run
This is kind of annoying when you get a small update to see so many fucking warnings. This scares user.
I am sure I will get plenty of requests to ask me to "UPDATE ASAP ALL THE PLUGINS".
You should just output this kind of notice once per instance.
Maybe in red or something. But not so many times... 

screen shot 2015-04-02 at 08 10 39

### PR DESCRIPTION
**Pull request by MoOx**
Close #272

### CODE REVIEW

**Comment by MoOx** [comment]
You can release that as a patch so people won't have to udpate everything asap.

**Comment by ai** [comment]
I put check to `warn` method 431bd99

**Comment by MoOx** [comment]
Even better. Thanks.

**Comment by ai** [comment]
Released in 4.1.1.

**Pull request closed without merging**
