### PR TITLE
Update plugins.md

### PR DESCRIPTION
**Pull request by martinkr**
I added a plugin to extract styles by mediaqueries and output them as separate files to the filesystem. If this is against the "approach" to modify the css stream and output a single fiel at the end, i totally understand if you reject this plugin. :) 

Cheers,

Martin

### CODE REVIEW

**Comment by ai** [comment]
CI fails on unknown `mediaqueries` word ;)

**Comment by martinkr** [comment]
Indeed there were some issues ;)

**Comment by ai** [comment]
@martinkr you can fix it by push commit to your branch.

**Comment by martinkr** [comment]
Everything's fine now https://travis-ci.org/martinkr/postcss-mediaquery-writer

**Comment by ai** [comment]
@martinkr still falling. You need to fix: `Extracts` → `extracts`, `mediaqueries` → `media queries`.

**Pull request closed without merging**
