### PR TITLE
Add protected methods

### PR DESCRIPTION
**Pull request by nex3**
These are useful when writing a package like the Sass parser that inherits from PostCSS types.

### CODE REVIEW

**Comment by ai** [comment]
Good additions

**Comment by ai** [comment]
Can you use version from `github` during your refactoring to make one release later?

**Comment by nex3** [comment]
> Can you use version from `github` during your refactoring to make one release later?

I'm not sure I understand what you mean by this.

**Comment by ai** [comment]
Do you need npm release?

**Comment by nex3** [comment]
Oh, I see. No, the changes that aren't yet released are things we can work around for now.

**Pull request merged**
