### PR TITLE
Support runtime plugin injection.

### PR DESCRIPTION
**Pull request by ben-eb**
Do we need more tests than this one? It is passing all current tests.

### CODE REVIEW

**Comment by ai** [comment]
I will accept it after lunch :)

**Comment by ai** [comment]
What if somebody will add plugins before itself?

```
(css, result) => {
    result.processor.plugins = [newOne].concat(result.processor.plugins);
}
```

Because we use just a array index in `lazyResult.currentPlugin` we wil have infinity loop.

Or we should ignore it as rare case?

**Comment by ben-eb** [comment]
I think we should ignore it for now. This functionality is more for supporting CodePen's use case; postcss-use only appends plugins to the current list. However if there is some valid use case that were to prepend plugins like you describe we can look at it then.

**Comment by ai** [comment]
Released in 4.1.15.

**Pull request merged**
