### PR TITLE
Add Chinese version doc README.cn.md

### PR DESCRIPTION
**Pull request by wenliangdai**

### CODE REVIEW

**Comment by ai** [comment]
@wenliangdai can you translate also

```
title="Philosopher’s stone, logo of PostCSS"
```

What is your Twitter account?

**Comment by ai** [comment]
Add `Sass` not `SASS`

**Comment by wenliangdai** [comment]
My twitter is @Wenliang_Dai and I‘ve made up the translation to image title and alt.

**Comment by ai** [comment]
@wenliangdai can you translate “CHinese translation” to Chinese?

**Comment by wenliangdai** [comment]
@ai "Chinese translation" => "中文翻译"

**Pull request merged**
